apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    app: httpd
spec:
  ports:
    - nodePort: 30002
      port: 80
      targetPort: 80
  selector:
    app: httpd
    tier: web
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv1
  labels:
    app: httpd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  selector:
    matchLabels:
      app: httpd
      tier: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: httpd
        tier: web
    spec:
      containers:
      - image: sarthakphatate/task6:v1
        name: httpd
        ports:
        - containerPort: 80
          name: httpd
        volumeMounts:
        - name: ps
          mountPath: /var/www/html
      volumes:
      - name: ps
        persistentVolumeClaim:
          claimName: pv1
