apiVersion: v1
kind: Service
metadata:
  name: httpd-server
spec:
  selector:
    type: http
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pvc
  labels:
    name: httpd-pvc


spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: httpd-server
  labels:
    type: http
spec:
  selector:
    matchLabels:
      type: http
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        type: http
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
          name: httpd
        volumeMounts:
        - name: httpd-storage
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: httpd-storage
        persistentVolumeClaim:
        
          claimName: http-pvc
